name: Github-Timeline-Backend CI/CD

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    env:
      GITHUB_JOBS_API: https://jobs.github.com/positions
      AUTH_SECRET: TEST+>SESSION+>SECRET
      ACCESS_TOKEN_URL: https://github.com/login/oauth/access_token
      REDIRECT_URL: https://github.com/login/oauth/authorize?
      GITHUB_CLIENT_ID: github_client_id
      CALLBACK_URL: CALLBACK_URL
